name: SwiftLint

on:
  pull_request:
    branches: [ develop ]
    paths:
      - '.github/workflows/swiftlint-macos.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run SwiftLint
        run: swiftlint lint --reporter github-actions-logging
